app.frontend.url=http://localhost:5173

# Base de données MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/gestion_lb_security
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

# JWT
jwt.secret=1tzw7kEKi5TB2I7J/+kNmaQQSPise1TongDlRaHDFWY3uaWPTsZ4GDuZVE3tIQASJi6eeYIaZ99RRhL9tdIlOA==
jwt.expiration=86400000

# Port
server.port=8085

# Upload fichiers (augmenter la limite par défaut de 1MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

# Mail Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre.adresse@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true